### ISSUE TITLE
Error compiling "loader"

### ISSUE THREAD

**Issue by DFL1973** [fbelavenuto/msx1fpga#10]
(...)
src/vdp.c:62: error 20: Undefined identifier 'VDP_CMD'
src/vdp.c:63: error 20: Undefined identifier 'VDP_CMD'
src/vdp.c:74: error 20: Undefined identifier 'VDP_DATA'
src/vdp.c:104: error 20: Undefined identifier 'VDP_DATA'
(...)

Seems the definition of "VDP_CMD" and "VDP_DATA" are missing from the sources

**Comment by fbelavenuto** [comment]
This project is not related to ARPL!

**Comment by fbelavenuto** [comment]
Hi, thanks for the report. Fixed now into commit 8ce655b90b8f7cf1e4ee6fb2bc75588185e46b98
