### ISSUE TITLE
CALL SYSTEM does not go to MSX-DOS

### ISSUE THREAD

**Issue by Chandler-Kluser** [fbelavenuto/msx1fpga#24]
It reboots to BASIC interpreter

**Comment by Chandler-Kluser** [comment]
More details: Board Altera DE2 with last week release.

https://github.com/fbelavenuto/msx1fpga/assets/29960960/b722b725-ab29-401e-bfa0-682a767cf1cd

**Comment by fbelavenuto** [comment]
Hi. Please do a test, update NEXTOR.SYS in your SD CARD to last version, 2.1.1-beta1:
https://github.com/Konamiman/Nextor/releases/download/v2.1.1-beta-1/NEXTOR.SYS

**Comment by Chandler-Kluser** [comment]
not working

**Comment by fbelavenuto** [comment]
I can't reproduce!!

Please test with a new SD Card with content from github.

![IMG_20240115_181957](https://github.com/fbelavenuto/msx1fpga/assets/11461290/863c8a2b-4064-48a5-94fd-81136f805d7d)

**Comment by Chandler-Kluser** [comment]
I have got exactly what is in the `Support/SD` path and copied to my FAT SD card, it booted to basic and when I hit CALL SYSTEM it still does not work... :disappointed: 

If there is any way to give any kind of debug or additional information, please, let me know

**Comment by Chandler-Kluser** [comment]
don't know if this helps, but when I call files it outputs `Disk offline`

**Comment by Chandler-Kluser** [comment]
The issue was actually the SD card used. Changing an SDXC for an SDHC solved the issue. God bless you, dear friend!
