### ISSUE TITLE
status of MiST port?

### ISSUE THREAD

**Issue by nippur72** [fbelavenuto/msx1fpga#6]
Hi, I noticed there is `mist` branch on this repo, so I compiled it and trying to make it run on a Mistica (a MiST 100% clone). I managed to arrive to the point where the ROM loader looks for the `EN.KMP` file, but it finds a wrong one of 937 bytes instead of 1024.

I understand this is due to the fact that the `mist` branch is 3 years old and the `.kmp` format has changed in the while. 

So may I ask you, what is the status of the MiST port? Is it running, needing only a correct keymap file, or was it just a work in progress? Do you plan to align it to the `master` branch someday? 

If it might help, I can do any test you require on my board. I also know a little bit of HDL (beginner level).

**Comment by fbelavenuto** [comment]
Hi,

I tried to port to MIST, but I couldn't. This branch will not be updated, I even need to delete it.

**Comment by ManuFerHi** [comment]
It is a pity that you do not update, I have tried and it boots me with the old keymaps, there are people who demand this core in mist / sidi.

**Comment by ManuFerHi** [comment]
It starts well, but it jumps from Nextor to basic,  happen before with the MSX2 core if you wanted to use Nextor, but the new mist framework already corrects this, I think that if you update the mist framework it will work very well.

**Comment by rampa069** [comment]
> Hi,
> 
> I tried to port to MIST, but I couldn't. This branch will not be updated, I even need to delete it.

Fabio, if you are interested, i have the mist port running. feel free to use code from it if you need! Thanks for this fantastic core. 

[Mist and SiDi port](https://github.com/RW-FPGA-devel-Team/MSX1FPGA_SiDi)

**Comment by fbelavenuto** [comment]
> > Hi,
> > I tried to port to MIST, but I couldn't. This branch will not be updated, I even need to delete it.
> 
> Fabio, if you are interested, i have the mist port running. feel free to use code from it if you need! Thanks for this fantastic core.
> 
> [Mist and SiDi port](https://github.com/RW-FPGA-devel-Team/MSX1FPGA_SiDi)

Thanks
